### ISSUE TITLE
AzureKubernetesService FQDN Tag on Firewall

### ISSUE THREAD

**Issue by haithamshahin333** [mspnp/aks-baseline#289]
Hi team,

Thanks for all the work here. Curious if there's a way to see the underlying FQDNs that are included in this tag on the [linked line](https://github.com/mspnp/aks-baseline/blob/e9bcd46d3473530a17a8645d139af50edaeead21/networking/hub-regionA.bicep#L568). I'm assuming it's [this list from the docs](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#azure-global-required-fqdn--application-rules) but wanted to know what the team's thoughts are since I noticed you also have a flux rule [linked here](https://github.com/mspnp/aks-baseline/blob/e9bcd46d3473530a17a8645d139af50edaeead21/networking/hub-regionA.bicep#L616) that includes some of these FQDNs explicitly.

**Comment by ckittel** [comment]
I'm not aware of any public documentation or API that lists specifically what's in any of our FW tags, as they are subject to change. And because they are subject to change, we listed what is likely "duplicates" in some of the specific rules.  The `AzureKubernetesService` FQDN tag only covers the core AKS service, no addons or extensions. It might indeed overlap with those, but that's not a documented "feature" just happens to be overlapping requirements.

**Comment by haithamshahin333** [comment]
Thanks @ckittel - another follow-up question, something that I want to validate and get your take on.

My understanding is that the "AzureKubernetesService" FQDN tag that we're applying here is not a tag that is the IP range of the potential API Server but is actually a tag that bundles/encompasses those set of required FQDNs needed by AKS for egress (things like mcr.microsoft.com for example). So makes sense, as they could potentially change in the future, the tag will "cover" you accordingly so you don't need to make any updates.

That's really what I want to confirm since I've seen it referenced differently and if it were in fact the IP Ranges then it wouldn't really apply when we are deploying private clusters as we do here.

Appreciate your input on this!

**Comment by ckittel** [comment]
It's to cover platform runtime requirements, that must be allowed, to have a supported system.  You can opt to add those in by hand, or you can use the tag -- but we document the outbound requirements (linked in your OP) so that you don't run into a situation where you contact support and they say "can't help you, you're blocking critical platform traffic."  Almost all services have some "outbound" requirements for them to function (even without you adding your own requirements on top of it), be that for platform health logging and telemetry or some implementation detail that needs to use a storage account or whatever or things, like you called out, MCR for platform-provided & maintained images/containers that are installed on your cluster (even before you show up to your cluster with your workloads).

The tag is going to be more permissive than necessary, because it casts a relatively wide net on coverage that spans many versions of the AKS platform (ancient to preview).  Opting instead for individual endpoints and making sure you stay current with them as the platform evolves will produce rules that are only as permissive as needed.

The tag can be used in private clusters for sure to cover the runtime requirements, otherwise you'll need to include those by hand, including your actual FQDN for your API server (or a regional wildcard if you'd rather not maintain it to be that granular).

Watch the Private Cluster v2 work unfold, as that will change the outbound requirements significantly.  Private clusters are moving to a new implementation that separates Azure's control plane requirements from the user's runtime requirements, so that your firewalls are not littered with "microsoft's decisions" and can be left to document your actual requirements.  https://github.com/Azure/AKS/issues/2729

**Comment by haithamshahin333** [comment]
Thank you @ckittel! Excellent input here, closing this from my side
