### ISSUE TITLE
Firewall Deployment Fails

### ISSUE THREAD

**Issue by jachin84** [mspnp/aks-baseline#336]
Running the following command for the Hub deployment results in the error below.

`az deployment group create -g rg-enterprise-networking-hubs -f networking/hub-default.bicep -p location=australiaeast`

```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"InternalServerError\",\r\n        \"message\": \"An error occurred.\",\r\n        \"details\": []\r\n      }\r\n    ]\r\n  }\r\n}"}]}}
```

**Comment by ckittel** [comment]
Sorry to hear that @jachin84.  The error you got was non-specific `"code": "InternalServerError"` which gives you or me no information to go off of, other than the resource provider crashed with an unhandled exception trying to perform your deployment.  Fun!  When you get an `InternalServerError` on any deployment, the only hope you've got to know exactly what it was, is to open a support ticket.  Otherwise, you're left with the option of "trying again and hope it was transient" or debugging via guessing -- neither are great use of your time though :) 

Sorry, we can't help with this specific error :(  If you do find out what it was, and it was indeed something in the implementation that is triggering the `500` HTTP response on the resource provider, please let us know!
