### ISSUE TITLE
How to setup browser redirect from root path to workload

### ISSUE THREAD

**Issue by ranul-pallemulle** [mspnp/aks-baseline#341]
I have followed this reference implementation for my AKS cluster, the only real difference being that I have used an nginx for the internal load balancer as opposed to Traefik.

Assume the Application Gateway is given the domain https://myapp.mycompany.com and the internal load balancer is given https://cluster.aks-ingress.myapp.mycompany.com. I have several workloads hosted in the cluster, one of which is the Home app which is given the path /home using an Ingress. If I access https://myapp.mycompany.com/home from my browser then the request is routed correctly to the Home application.

My requirement is that if someone tries to access https://myapp.mycompany.com in their browser they should be redirected to https://myapp.mycompany.com/home, since the former does not have any associated workload and simply returns a 404. I have searched for ways to do this using Application Gateway to no avail. I have also tried using the nginx.ingress.kubernetes.io/app-root annotation but that redirects the user to a URL containing the internal host name (i.e. https://cluster.aks-ingress.myapp.mycompany.com/home).

Any help would be much appreciated.

**Comment by ranul-pallemulle** [comment]
I have temporarily solved this by creating a deployment, service and ingress at the root path (i.e /) just for serving up an html page. The html page runs a single line of JavaScript:
window.location.href = "/home"

**Comment by ckittel** [comment]
I'm not overly familiar with nginx's ingress configuration, but take a look at [`nginx.ingress.kubernetes.io/rewrite-target`](https://kubernetes.github.io/ingress-nginx/examples/rewrite/) to see if you can do a rewrite for root and do the redirect in your `Ingress` resource.  Alternatively, Azure Application Gateway also has [rewrite rules](https://learn.microsoft.com/azure/application-gateway/rewrite-http-headers-url#url-path-and-query-string) that you might be able to use, so you can offload that to your application gateway instead of consuming in-cluster processing.

This AKS Baseline team will not be able to support you in this request, unfortunately.  But hopefully one of the two links will get you up and running without the need for the "fake" workload out there.
